export enum SocketEvents {
    CONNECTION = 'connection',
    DISCONNECT = 'disconnect',
    JOIN_GAME = 'join-game',
    LEAVE_GAME = 'leave-game',
    START_GAME = 'start-game',
    GAME_STARTED = 'game-started',
    PLAYER_JOINED = 'player-joined',
    PLAYER_LEFT = 'player-left',
    PLAYER_DISCONNECTED = 'player-disconnected',
    NEXT_QUESTION = 'next-question',
    SUBMIT_ANSWER = 'submit-answer',
    ANSWER_SUBMITTED = 'answer-submitted',
    PLAYER_ANSWERED = 'player-answered',
    SHOW_RESULTS = 'show-results',
    QUESTION_RESULTS = 'question-results',
    END_GAME = 'end-game',
    GAME_ENDED = 'game-ended',
    ERROR = 'error',
    PING = 'ping',
    PONG = 'pong'
}